-- DDL (Data Definition Language)
-- Creating Tables

CREATE TABLE doctors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR2(20) NOT NULL,
    lname VARCHAR2(20) NOT NULL,
    speciality VARCHAR2(20) NOT NULL,
    phone_no CHAR(10) NOT NULL
);

CREATE TABLE patients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR2(20) NOT NULL,
    lname VARCHAR2(20) NOT NULL,
    dob DATE NOT NULL,
    height NUMBER(3,2) NOT NULL,
    weight NUMBER(5,2) NOT NULL,
    phone_no CHAR(10)
);

CREATE TABLE rooms (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_no CHAR(3) NOT NULL
);

CREATE TABLE prescription_counters (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counter_no CHAR(3) NOT NULL
);

CREATE TABLE appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id NUMBER NOT NULL,
    patient_id NUMBER NOT NULL,
    room_id NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIMESTAMP NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE treatment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    prescription VARCHAR2(20) NOT NULL,
    counter_id NUMBER NOT NULL,
    treatment_date DATE NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (counter_id) REFERENCES prescription_counters(id)
);

-- DML (Data Manipulation Language)
-- Inserting Data

INSERT INTO doctors (fname, lname, speciality, phone_no) 
VALUES ('Karangwa', 'Aliane', 'Cardiology', '0784567890');

INSERT INTO doctors (fname, lname, speciality, phone_no) 
VALUES ('Mukiza', 'Claudette', 'Neurology', '0795678901');

INSERT INTO doctors (fname, lname, speciality, phone_no) 
VALUES ('Niwemwana', 'Odette', 'Pediatrics', '0736789012');

INSERT INTO doctors (fname, lname, speciality, phone_no) 
VALUES ('Nkuranga', 'Chantal', 'Orthopedics', '0727890123');

INSERT INTO doctors (fname, lname, speciality, phone_no) 
VALUES ('Ufitikirezi', 'Eugenie', 'Dermatology', '0788901234');


INSERT INTO patients (fname, lname, dob, height, weight, phone_no) 
VALUES ('Mukunzi', 'Belyse', TO_DATE('1980-09-22', 'YYYY-MM-DD'), 1.75, 78.50, '0784567890');

INSERT INTO patients (fname, lname, dob, height, weight, phone_no) 
VALUES ('Gikundiro', 'Rosine', TO_DATE('1950-01-30', 'YYYY-MM-DD'), 1.65, 68.25, '0787654321');

INSERT INTO patients (fname, lname, dob, height, weight, phone_no) 
VALUES ('Irahari', 'Nadine', TO_DATE('1949-12-05', 'YYYY-MM-DD'), 1.70, 82.10, '0795678901');

INSERT INTO patients (fname, lname, dob, height, weight, phone_no) 
VALUES ('Nshuti', 'Braille', TO_DATE('1965-03-11', 'YYYY-MM-DD'), 1.80, 90.45, '0736789012');

INSERT INTO patients (fname, lname, dob, height, weight, phone_no) 
VALUES ('Mukunzi', 'Yannick', TO_DATE('2010-06-15', 'YYYY-MM-DD'), 1.30, 35.30, '0797890123');


INSERT INTO rooms (room_no) VALUES ('101');
INSERT INTO rooms (room_no) VALUES ('102');
INSERT INTO rooms (room_no) VALUES ('103');
INSERT INTO rooms (room_no) VALUES ('104');
INSERT INTO rooms (room_no) VALUES ('105');


INSERT INTO prescription_counters (counter_no) VALUES ('201');
INSERT INTO prescription_counters (counter_no) VALUES ('202');
INSERT INTO prescription_counters (counter_no) VALUES ('203');
INSERT INTO prescription_counters (counter_no) VALUES ('204');
INSERT INTO prescription_counters (counter_no) VALUES ('205');


INSERT INTO appointments (doctor_id, patient_id, room_id, appointment_date, appointment_time) 
VALUES (1, 5, 1, TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'));

INSERT INTO appointments (doctor_id, patient_id, room_id, appointment_date, appointment_time) 
VALUES (2, 4, 2, TO_DATE('2024-07-02', 'YYYY-MM-DD'), TO_TIMESTAMP('10:00:00', 'HH24:MI:SS'));

INSERT INTO appointments (doctor_id, patient_id, room_id, appointment_date, appointment_time) 
VALUES (3, 3, 3, TO_DATE('2024-07-03', 'YYYY-MM-DD'), TO_TIMESTAMP('11:00:00', 'HH24:MI:SS'));

INSERT INTO appointments (doctor_id, patient_id, room_id, appointment_date, appointment_time) 
VALUES (4, 2, 4, TO_DATE('2024-07-04', 'YYYY-MM-DD'), TO_TIMESTAMP('14:00:00', 'HH24:MI:SS'));

INSERT INTO appointments (doctor_id, patient_id, room_id, appointment_date, appointment_time) 
VALUES (5, 1, 5, TO_DATE('2024-07-05', 'YYYY-MM-DD'), TO_TIMESTAMP('15:00:00', 'HH24:MI:SS'));


INSERT INTO treatment (patient_id, prescription, counter_id, treatment_date) 
VALUES (1, 'Aspirin', 5, TO_DATE('2024-07-01', 'YYYY-MM-DD'));

INSERT INTO treatment (patient_id, prescription, counter_id, treatment_date) 
VALUES (2, 'Ibuprofen', 4, TO_DATE('2024-07-02', 'YYYY-MM-DD'));

INSERT INTO treatment (patient_id, prescription, counter_id, treatment_date) 
VALUES (3, 'Amoxicillin', 3, TO_DATE('2024-07-03', 'YYYY-MM-DD'));

INSERT INTO treatment (patient_id, prescription, counter_id, treatment_date) 
VALUES (4, 'Paracetamol', 2, TO_DATE('2024-07-04', 'YYYY-MM-DD'));

INSERT INTO treatment (patient_id, prescription, counter_id, treatment_date) 
VALUES (5, 'Metformin', 1, TO_DATE('2024-07-05', 'YYYY-MM-DD'));


-- Updating Data

UPDATE patients
SET height = 1.76
WHERE id = 1;

-- Deleting Data

DELETE FROM appointments
WHERE id = 5;

DELETE FROM patients
WHERE id = 5;

-- Part 3: Data Retrieval (Joins and Subqueries)
-- Retrieve appointment details using JOINs

SELECT 
    p.fname || ' ' || p.lname AS patient_name,
    d.fname || ' ' || d.lname AS doctor_name,
    d.speciality AS specialty,
    r.room_no AS room_number,
    a.appointment_date,
    a.appointment_time
FROM appointments a
JOIN patients p ON a.patient_id = p.id
JOIN doctors d ON a.doctor_id = d.id
JOIN rooms r ON a.room_id = r.id;

-- Subquery example to find patients older than a certain age

SELECT fname, lname, dob
FROM patients
WHERE dob < (SELECT ADD_MONTHS(SYSDATE, -12*30) FROM dual);  -- Patients older than 30 years

-- DCL (Data Control Language) - Granting and Revoking Privileges
-- Granting permissions

GRANT ALL PRIVILEGES TO leon;

-- Revoking permissions

REVOKE SELECT, UPDATE ON doctors FROM leon;

-- TCL (Transaction Control Language)
-- Committing the transaction

COMMIT;

-- Rolling back a transaction example (if required)

ROLLBACK;
